services:
  web:
    build: .
    container_name: clicker_web
    ports:
      - 5000:5000
    depends_on:
      - redis
    volumes:
      - ./app.py:/app/app.py

  redis:
    image: redis:8.4.0-alpine
    container_name: clicker_redis
    volumes:
      - redis_data:/data

volumes:
  redis_data:


