services:
  web:
    build: .
    container_name: clicker_web
    ports:
      - 5000:5000
    depends_on:
      - redis
    volumes:
      - ./app.py:/app/app.py

  redis:
    image: redis:8.4.0-alpine
    container_name: clicker_redis
    volumes:
      - redis_data:/data

  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
      
volumes:
  redis_data:


